name = "plaza-replica"
version = "0.1.1"
dryrun = false
home = ".replica"
logging_config = "config/console.yaml"
targets = ["/Volumes/plaza/plaza", "dpw@piedmont.local:backups/plaza", "dpw@orinda.local:.backups/plaza"]
source_folders = ["photos", "Music", ".local/bin" ]
files = [ ".age/decrypt.sh", ".age/encrypt.sh", ".age/key.enc", ".alias", ".config", ".motd", ".profile", ".ssh/authorized_keys", ".ssh/plaza.pub", ".zprofile", ".zshenv", ".zshrc" ]
compress = false
encrypt = false
