name = "piedmont-keys-client"
service_scheme = "http"
service_host = "piedmont.local"
service_port = 28200
connect_timeout = 3 # seconds
logging_config = "config/console.yaml"
apikey = "3678fde6af84c28f93667fd9623ae6df"
session = "8NUs7e2uyYV2snc7"
