name = "test-replica"
version = "0.1.1"
home = "./"
logging_config = ".replica/config/console.yaml"
targets = ["tback"]
source_folders = [ ".config" ]
files = [ 
    "file1.txt",
    "file2.txt",
    "big-file.pdf",
]
excludes = []
dbfile = ".replica/data/files.json"
compress = false
encrypt = false
dryrun = false
verbose = false
