appenders:
  file:
    kind: rolling_file
    path: ".replica/logs/replica.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%s)(utc)} [{f}:{L}] - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 100kb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: ".replica/logs/rolled-replica.{}.log"
root:
  level: info
  appenders:
    - file
