name = "test-replica"
version = "0.1.1"
home = ""
logging_config = ".replica/config/console.yaml"
targets = ["/tmp/junk"]
source_folders = [ ".config" ]
files = [ 
    ".motd",
    ".profile",
    ".zshrc",
]
dbfile = ".replica/data/files.json"
compress = false
encrypt = false
