appenders:
  file:
    kind: rolling_file
    path: "logs/current-key-service.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%s)(utc)} [{f}:{L}] - {h({l})}: {M}:{m}{n}"
    policy:
      trigger:
        kind: size
        limit: 250kb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "logs/rolled-key-service.{}.log"
root:
  level: info
  appenders:
    - file
